export const START_DATE = new Date('2026-06-21');

export const AH_QS = [
  { n: 'Contains Duplicate', d: 'E' },
  { n: 'Valid Anagram', d: 'E' },
  { n: 'Two Sum', d: 'E' },
  { n: 'Group Anagrams', d: 'M' },
  { n: 'Top K Frequent Elements', d: 'M' },
  { n: 'Product of Array Except Self', d: 'M' },
  { n: 'Encode and Decode Strings', d: 'M' },
  { n: 'Longest Consecutive Sequence', d: 'M' },
];

export const WEEKS = [
  {
    title: 'Week 1 — Arrays & Hashing',
    sub: 'Jun 14–20',
    done: true,
    focus: 'Foundation: HashMap, HashSet, frequency maps',
    days: [],
  },
  {
    title: 'Week 2 — Two Pointers + Sliding Window',
    sub: 'Jun 21–27',
    focus: 'Revision today · Two Pointers + Sliding Window Mon–Fri',
    days: [
      { lbl: 'Sun', off: 0, type: 'today', rev: true, note: 'Revise Arrays & Hashing from memory. Tick each one as you re-solve it without hints.', qs: AH_QS },
      { lbl: 'Mon', off: 1, type: 'active', qs: [{ n: 'Valid Palindrome', d: 'E' }, { n: 'Two Sum II', d: 'M' }, { n: '3Sum', d: 'M' }] },
      { lbl: 'Tue', off: 2, type: 'active', qs: [{ n: 'Container With Most Water', d: 'M' }, { n: 'Trapping Rain Water', d: 'H' }] },
      { lbl: 'Wed', off: 3, type: 'active', qs: [{ n: 'Best Time to Buy & Sell Stock', d: 'E' }, { n: 'Longest Substring Without Repeating', d: 'M' }] },
      { lbl: 'Thu', off: 4, type: 'active', qs: [{ n: 'Longest Repeating Character Replacement', d: 'M' }, { n: 'Permutation in String', d: 'M' }] },
      { lbl: 'Fri', off: 5, type: 'active', qs: [{ n: 'Minimum Window Substring', d: 'H' }] },
      { lbl: 'Sat', off: 6, type: 'buffer', qs: [], note: 'Revise sliding window. Key: when to expand vs shrink. Re-solve Longest Substring Without Repeating from scratch.' },
    ],
  },
  {
    title: 'Week 3 — Stack + Binary Search',
    sub: 'Jun 28–Jul 4',
    focus: 'Stack patterns and binary search variants',
    days: [
      { lbl: 'Sun', off: 7, type: 'buffer', qs: [], note: 'Mock: 2 random Two Pointers/Sliding Window questions with 20 min timer. No hints.' },
      { lbl: 'Mon', off: 8, type: 'active', qs: [{ n: 'Valid Parentheses', d: 'E' }, { n: 'Min Stack', d: 'M' }] },
      { lbl: 'Tue', off: 9, type: 'active', qs: [{ n: 'Evaluate Reverse Polish Notation', d: 'M' }, { n: 'Generate Parentheses', d: 'M' }] },
      { lbl: 'Wed', off: 10, type: 'active', qs: [{ n: 'Daily Temperatures', d: 'M' }, { n: 'Binary Search', d: 'E' }] },
      { lbl: 'Thu', off: 11, type: 'active', qs: [{ n: 'Search a 2D Matrix', d: 'M' }, { n: 'Find Minimum in Rotated Sorted Array', d: 'M' }] },
      { lbl: 'Fri', off: 12, type: 'active', qs: [{ n: 'Search in Rotated Sorted Array', d: 'M' }, { n: 'Koko Eating Bananas', d: 'M' }, { n: 'Time Based Key-Value Store', d: 'M' }] },
      { lbl: 'Sat', off: 13, type: 'buffer', qs: [], note: 'Revise 3 binary search variants: plain, rotated array, answer-space (Koko). These cover 80% of BS questions.' },
    ],
  },
  {
    title: 'Week 4 — Linked List',
    sub: 'Jul 5–11',
    focus: 'Pointer manipulation, slow/fast pointers, LRU Cache',
    days: [
      { lbl: 'Sun', off: 14, type: 'buffer', qs: [], note: 'Mock: 3 questions from weeks 2–3 timed. First 4-week checkpoint.' },
      { lbl: 'Mon', off: 15, type: 'active', qs: [{ n: 'Reverse Linked List', d: 'E' }, { n: 'Merge Two Sorted Lists', d: 'E' }, { n: 'Linked List Cycle', d: 'E' }] },
      { lbl: 'Tue', off: 16, type: 'active', qs: [{ n: 'Remove Nth Node From End', d: 'M' }, { n: 'Reorder List', d: 'M' }] },
      { lbl: 'Wed', off: 17, type: 'active', qs: [{ n: 'Copy List with Random Pointer', d: 'M' }, { n: 'Add Two Numbers', d: 'M' }] },
      { lbl: 'Thu', off: 18, type: 'active', qs: [{ n: 'Find the Duplicate Number', d: 'M' }] },
      { lbl: 'Fri', off: 19, type: 'active', qs: [{ n: 'LRU Cache', d: 'M' }] },
      { lbl: 'Sat', off: 20, type: 'buffer', qs: [], note: 'LRU Cache is critical for BFSI. Implement from scratch: HashMap + Doubly Linked List. Spend extra time here.' },
    ],
  },
  {
    title: 'Week 5 — Trees (Part 1)',
    sub: 'Jul 12–18',
    focus: 'DFS/BFS on trees, BST properties, recursion patterns',
    days: [
      { lbl: 'Sun', off: 21, type: 'buffer', qs: [], note: 'Mock: 3 Linked List questions. Can you implement LRU Cache without any notes?' },
      { lbl: 'Mon', off: 22, type: 'active', qs: [{ n: 'Invert Binary Tree', d: 'E' }, { n: 'Maximum Depth of Binary Tree', d: 'E' }, { n: 'Same Tree', d: 'E' }] },
      { lbl: 'Tue', off: 23, type: 'active', qs: [{ n: 'Diameter of Binary Tree', d: 'E' }, { n: 'Balanced Binary Tree', d: 'E' }] },
      { lbl: 'Wed', off: 24, type: 'active', qs: [{ n: 'Binary Tree Level Order Traversal', d: 'M' }, { n: 'Binary Tree Right Side View', d: 'M' }] },
      { lbl: 'Thu', off: 25, type: 'active', qs: [{ n: 'Subtree of Another Tree', d: 'E' }, { n: 'Count Good Nodes in Binary Tree', d: 'M' }] },
      { lbl: 'Fri', off: 26, type: 'active', qs: [{ n: 'Validate Binary Search Tree', d: 'M' }, { n: 'Kth Smallest Element in BST', d: 'M' }] },
      { lbl: 'Sat', off: 27, type: 'buffer', qs: [], note: 'Trees are recursion-heavy. Write recursive solutions: base case first, then recursive case.' },
    ],
  },
  {
    title: 'Week 6 — Trees (Part 2) + Heap + Intervals',
    sub: 'Jul 19–25',
    focus: 'BST ops, priority queues, top-K pattern, interval merging',
    days: [
      { lbl: 'Sun', off: 28, type: 'buffer', qs: [], note: 'BFS vs DFS: when to use which? Re-solve Level Order Traversal (BFS) and Max Depth (DFS).' },
      { lbl: 'Mon', off: 29, type: 'active', qs: [{ n: 'Lowest Common Ancestor of BST', d: 'M' }] },
      { lbl: 'Tue', off: 30, type: 'active', qs: [{ n: 'Kth Largest Element in Stream', d: 'E' }, { n: 'Last Stone Weight', d: 'E' }, { n: 'K Closest Points to Origin', d: 'M' }] },
      { lbl: 'Wed', off: 31, type: 'active', qs: [{ n: 'Kth Largest Element in Array', d: 'M' }, { n: 'Task Scheduler', d: 'M' }] },
      { lbl: 'Thu', off: 32, type: 'active', qs: [{ n: 'Design Twitter', d: 'M' }, { n: 'Insert Interval', d: 'M' }] },
      { lbl: 'Fri', off: 33, type: 'active', qs: [{ n: 'Merge Intervals', d: 'M' }, { n: 'Non-overlapping Intervals', d: 'M' }, { n: 'Meeting Rooms', d: 'E' }, { n: 'Meeting Rooms II', d: 'M' }] },
      { lbl: 'Sat', off: 34, type: 'buffer', qs: [], note: 'Java PriorityQueue is min-heap by default. Practice reversing with comparator for max-heap. Heap+HashMap is a common BFSI combo.' },
    ],
  },
  {
    title: 'Week 7 — Graphs',
    sub: 'Jul 26–Aug 1',
    focus: 'BFS/DFS on grids, topological sort, connected components',
    days: [
      { lbl: 'Sun', off: 35, type: 'buffer', qs: [], note: 'Mock: 2 tree + 1 heap question timed. Speak your thought process out loud.' },
      { lbl: 'Mon', off: 36, type: 'active', qs: [{ n: 'Number of Islands', d: 'M' }, { n: 'Max Area of Island', d: 'M' }] },
      { lbl: 'Tue', off: 37, type: 'active', qs: [{ n: 'Clone Graph', d: 'M' }, { n: 'Rotting Oranges', d: 'M' }] },
      { lbl: 'Wed', off: 38, type: 'active', qs: [{ n: 'Pacific Atlantic Water Flow', d: 'M' }, { n: 'Surrounded Regions', d: 'M' }] },
      { lbl: 'Thu', off: 39, type: 'active', qs: [{ n: 'Course Schedule', d: 'M' }, { n: 'Course Schedule II', d: 'M' }] },
      { lbl: 'Fri', off: 40, type: 'active', qs: [{ n: 'Number of Connected Components', d: 'M' }] },
      { lbl: 'Sat', off: 41, type: 'buffer', qs: [], note: 'Topological sort: practice both BFS (Kahn\'s) and DFS-based. Course Schedule is a must-know for BFSI.' },
    ],
  },
  {
    title: 'Week 8 — Backtracking + Bit Manipulation',
    sub: 'Aug 2–8',
    focus: 'Backtracking template, bit tricks, math patterns',
    days: [
      { lbl: 'Sun', off: 42, type: 'buffer', qs: [], note: 'Number of Islands — solve BFS and DFS both. Both versions appear in interviews.' },
      { lbl: 'Mon', off: 43, type: 'active', qs: [{ n: 'Permutations', d: 'M' }, { n: 'Subsets', d: 'M' }] },
      { lbl: 'Tue', off: 44, type: 'active', qs: [{ n: 'Combination Sum', d: 'M' }, { n: 'Letter Combinations Phone Number', d: 'M' }] },
      { lbl: 'Wed', off: 45, type: 'active', qs: [{ n: 'Word Search', d: 'M' }] },
      { lbl: 'Thu', off: 46, type: 'active', qs: [{ n: 'Single Number', d: 'E' }, { n: 'Missing Number', d: 'E' }, { n: 'Number of 1 Bits', d: 'E' }, { n: 'Counting Bits', d: 'E' }] },
      { lbl: 'Fri', off: 47, type: 'active', qs: [{ n: 'Reverse Bits', d: 'E' }, { n: 'Reverse Integer', d: 'M' }, { n: 'Happy Number', d: 'E' }] },
      { lbl: 'Sat', off: 48, type: 'buffer', qs: [], note: 'Backtracking template: choose → explore → unchoose. Write this from scratch. All backtracking problems follow this one pattern.' },
    ],
  },
  {
    title: 'Week 9 — Dynamic Programming',
    sub: 'Aug 9–15',
    focus: '1D DP, 2D DP, memoization vs tabulation',
    days: [
      { lbl: 'Sun', off: 49, type: 'buffer', qs: [], note: 'Full mock: 4 questions from weeks 7–8, 25 min each. No hints, timer running.' },
      { lbl: 'Mon', off: 50, type: 'active', qs: [{ n: 'Climbing Stairs', d: 'E' }, { n: 'Min Cost Climbing Stairs', d: 'E' }, { n: 'House Robber', d: 'M' }] },
      { lbl: 'Tue', off: 51, type: 'active', qs: [{ n: 'House Robber II', d: 'M' }, { n: 'Coin Change', d: 'M' }] },
      { lbl: 'Wed', off: 52, type: 'active', qs: [{ n: 'Longest Palindromic Substring', d: 'M' }, { n: 'Palindromic Substrings', d: 'M' }] },
      { lbl: 'Thu', off: 53, type: 'active', qs: [{ n: 'Decode Ways', d: 'M' }, { n: 'Word Break', d: 'M' }] },
      { lbl: 'Fri', off: 54, type: 'active', qs: [{ n: 'Maximum Product Subarray', d: 'M' }, { n: 'Jump Game', d: 'M' }, { n: 'Longest Increasing Subsequence', d: 'M' }] },
      { lbl: 'Sat', off: 55, type: 'buffer', qs: [], note: 'Recurrence relation is everything in DP. Review Coin Change and Climbing Stairs as the two canonical DP templates.' },
    ],
  },
  {
    title: 'Week 10 — DP (cont.) + Math & Final Revision',
    sub: 'Aug 16–22',
    focus: 'Wrap up, full revision, mock interviews',
    days: [
      { lbl: 'Sun', off: 56, type: 'buffer', qs: [], note: 'Warmup DP: Unique Paths and Longest Common Subsequence before the week starts.' },
      { lbl: 'Mon', off: 57, type: 'active', qs: [{ n: 'Unique Paths', d: 'M' }, { n: 'Longest Common Subsequence', d: 'M' }] },
      { lbl: 'Tue', off: 58, type: 'active', qs: [{ n: 'Rotate Image', d: 'M' }, { n: 'Spiral Matrix', d: 'M' }, { n: 'Set Matrix Zeroes', d: 'M' }, { n: 'Plus One', d: 'E' }] },
      { lbl: 'Wed', off: 59, type: 'revision', qs: [], note: 'Revision — Arrays, Hashing, Two Pointers, Sliding Window, Stack, Binary Search. Re-solve 1 question from each without notes.' },
      { lbl: 'Thu', off: 60, type: 'revision', qs: [], note: 'Revision — Linked List, Trees, Heap, Graphs, DP. Re-solve 1 question from each without notes.' },
      { lbl: 'Fri', off: 61, type: 'revision', qs: [], note: 'Revision — anything shaky. Focus on complexity explanations.' },
      { lbl: 'Sat', off: 62, type: 'buffer', qs: [], note: 'Final mock: 3 questions, 30 min each. Speak out loud. You\'ve completed the core NeetCode BFSI list. 🎉' },
    ],
  },
];
